
%
% boss_db Record definition
%
% compile:
%	erl> boss_record_compiler:compile("page.erl",[{out_dir,"."}]).
%
% use:
%	erl> boss_record_lib:attribute_names(page).
%	[id,page_title,page_text]
%
%	erl> P = page:new(1,"La guerre des mondes","H.G. Wells").
%	erl> page:attribute_names(P)
%	[id,page_title,page_text]
%
%	erl> page:do_something(P)
%	ok
%
%	{ok,Pid}=boss_db:start([{adapter,mnesia}]).
%	boss_news:start()
%	mnesia:create_table(_ids_, [{attributes, [type, id]}]).
%	mnesia:create_table(page, [{attributes, page:attribute_names(Page)}]).
%
%	P.save().
%
% NOTES:
%	- if we set 'id' atom for Id object value (page:new(id, ...)); id will be autogenerated (in the form object-number, ie 'page-23')
%	- boss_news require an id in the form object-number, or fail
%

-module(page, [Id, PageTitle::string(), PageText::binary(), Words::integer()]).
-compile(export_all).

do_something() ->
	% doing something
	io:format(user, "doing something~n",[]),
	ok.

